version: 0.0
os: linux
files:
  - source: .
  - destination: /root/ 

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  Install:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh