name: Dev Code Test 

run-name: Deploying development code to ECS, ${{ github.actor }}

on:
  pull_request:
    branches: [ "testECS" ]
  workflow_dispatch:

env:
  AWS_REGION: "ap-southeast-2"
  STACK_NAME: "stackVerlBlog"

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK bootstrap
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "bootstrap"
          cdk_stack: ${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
          actions_comment: false
          working_dir: "cdk/"
     
      - name: CDK diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          actions_comment: true
          working_dir: "cdk/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $AWS_REGION
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

      - name: CDK deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "stackVerlBlog"
          cdk_args: "--require-approval never"
          actions_comment: false
          working_dir: "cdk/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $AWS_REGION

      - name: CDK synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "synth"
          cdk_version: "2.140.0"
          working_dir: "cdk/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $AWS_REGION
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}