name: Build/Deploy

run-name: Build/Deploy by ${{ github.actor}}

# Controls when the workflow will run
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUCKET_NAME: "bucketverlblog"
  AWS_REGION: "ap-southeast-2"

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun construct
      - run: mkdir revision
      - run: cp -R build/index.js scripts/run.sh appspec.yml revision
      - uses: actions/upload-artifact@v4
        with:
          name: buildOutput
          path: revision/

    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: buildOutput
      - run: 
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::851725333784:role/roleGitHubActionsVerlBlog
          role-session-name: roleSessionGitHubActionsVerlBlog
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 cp ./index.js s3://${{ env.BUCKET_NAME }}/

